### ISSUE TITLE
Chapter 11 missing!

### ISSUE THREAD

**Issue by erfanms** [PacktPublishing/Ensemble-Machine-Learning-Cookbook#3]
No code/ Resources for Chapter 11 provided.

**Comment by shubham763** [comment]
Hi @erfanms 

I've updated the files for chapter 11, sorry for the trouble. Thanks for noticing this and letting us know.
https://github.com/PacktPublishing/Ensemble-Machine-Learning-Cookbook/tree/master/Chapter11

Regards,
Shubham
